import { describe, expect, it } from "vitest";
import { NEUTRAL_OPTIONS } from "@/lib/studio/options";
import { DIGITAL_SOURCE_TYPES, LABEL_BY_PATH, buildProvenance, parseProvenance, summarizeProvenance, xmpPacket } from "@/lib/studio/provenance";

const base = { mode: "CLEAN_STUDIO" as const, sourcePhotoId: "photo_1", options: NEUTRAL_OPTIONS, mirrored: false, colourBalanced: false, createdAt: new Date("2026-09-16T10:00:00Z") };

describe("provenance builder", () => {
  it("labels composites as AI background with the composite digital source type", () => {
    const p = buildProvenance({ ...base, path: "composite", segmentationProvider: "photoroom", generatorProvider: null, scale: 1, background: { kind: "studio-sweep" } });
    expect(p.aiGenerated).toBe(true);
    expect(p.label).toBe("AI background");
    expect(p.digitalSourceType).toBe(DIGITAL_SOURCE_TYPES.composite);
    expect(p.itemPixels).toBe("preserved");
    expect(p.description).toMatch(/item pixels unaltered/);
    expect(p.description).toMatch(/rendered locally/);
    const scaled = buildProvenance({ ...base, path: "composite", segmentationProvider: "runpod", generatorProvider: null, scale: 0.8 });
    expect(scaled.itemPixels).toBe("scaled");
    const generated = buildProvenance({ ...base, mode: "LIFESTYLE", path: "composite", segmentationProvider: "runpod", generatorProvider: "photoroom-edit", model: "v2" });
    expect(generated.description).toMatch(/generated by a trained model/);
  });

  it("enhance, detail and condition are not AI-generated and keep the capture source type", () => {
    const e = buildProvenance({ ...base, path: "enhance", segmentationProvider: null, generatorProvider: null, notes: ["No provider"] });
    expect(e).toMatchObject({ aiGenerated: false, label: LABEL_BY_PATH.enhance, digitalSourceType: DIGITAL_SOURCE_TYPES.capture, itemPixels: "preserved", notes: ["No provider"] });
    const d = buildProvenance({ ...base, mode: "DETAIL", path: "detail", segmentationProvider: null, generatorProvider: null });
    expect(d.itemPixels).toBe("resampled");
    expect(d.label).toBe("Detail crop");
    const c = buildProvenance({ ...base, mode: "CONDITION", path: "condition", segmentationProvider: null, generatorProvider: null, colourBalanced: true });
    expect(c.label).toBe("Condition");
    expect(c.description).toMatch(/defects preserved/);
    expect(c.description).toMatch(/colour balance adjusted/);
  });

  it("emits an XMP packet with IPTC DigitalSourceType and a Dublin Core description", () => {
    const p = buildProvenance({ ...base, path: "composite", segmentationProvider: "photoroom", generatorProvider: null, model: "seg-v1" });
    const xmp = xmpPacket(p);
    expect(xmp).toContain('<?xpacket begin="');
    expect(xmp).toContain(`<Iptc4xmpExt:DigitalSourceType>${DIGITAL_SOURCE_TYPES.composite}</Iptc4xmpExt:DigitalSourceType>`);
    expect(xmp).toContain("<dc:description><rdf:Alt><rdf:li xml:lang=\"x-default\">Background replaced by Clover Studio");
    expect(xmp).toContain("<clover:aiGenerated>true</clover:aiGenerated>");
    expect(xmp).toContain("segmentation=photoroom; model=seg-v1");
    expect(xmp).toContain("<xmp:CreateDate>2026-09-16T10:00:00.000Z</xmp:CreateDate>");
  });

  it("escapes XML in the label-derived fields", () => {
    const p = buildProvenance({ ...base, mode: "CONDITION", path: "condition", segmentationProvider: null, generatorProvider: null, options: { ...NEUTRAL_OPTIONS, label: "<scratch> & \"dent\"" } });
    const xmp = xmpPacket({ ...p, mode: "A<B" });
    expect(xmp).toContain("<clover:mode>A&lt;B</clover:mode>");
  });

  it("round-trips through JSON and summarises for the client", () => {
    const p = buildProvenance({ ...base, path: "composite", segmentationProvider: "photoroom", generatorProvider: null, qa: { status: "pass", reason: "Same item", provider: "anthropic" }, outputs: { pngKey: "k.png", xmp: true } });
    const parsed = parseProvenance(JSON.parse(JSON.stringify(p)));
    expect(parsed).toEqual(p);
    const s = summarizeProvenance(parsed!);
    expect(s).toMatchObject({ label: "AI background", modeName: "Clean studio", hasPng: true, qa: { status: "pass" } });
    expect(parseProvenance({ pipeline: "upload", originalKey: "x" })).toBeNull();
    expect(parseProvenance(null)).toBeNull();
  });
});
